/**
 * `@assure-ai/whatsapp-types` — provider-facing types for Meta's WhatsApp
 * Business Platform Cloud API, plus Assure's normalized event contract.
 *
 * This package is types and small pure parsers. It performs no network I/O,
 * reads no environment, has no runtime dependencies, and holds no state.
 *
 * It is an independent Assure wrapper. It is not published, endorsed, or
 * reviewed by Meta, and Meta's official documentation and policies remain
 * authoritative for everything described here. See `docs/maintainers.md` for
 * the exact documents each type was derived from and when they were read.
 */

export {
  WhatsAppIdentifierError,
  asAssureLocale,
  asBusinessId,
  asE164PhoneNumber,
  asGraphApiVersion,
  asMetaAppId,
  asPagingCursor,
  asPhoneNumberId,
  asProviderLocaleCode,
  asTemplateId,
  asWabaId,
  asWhatsAppMessageId,
  asWhatsAppRecipient,
  isSameDestination,
  toE164PhoneNumber,
  toWhatsAppRecipient,
  type AssureLocale,
  type Brand,
  type BusinessId,
  type E164PhoneNumber,
  type GraphApiVersion,
  type MetaAppId,
  type PagingCursor,
  type PhoneNumberId,
  type ProviderLocaleCode,
  type TemplateId,
  type WabaId,
  type WhatsAppMessageId,
  type WhatsAppRecipient,
} from './brands.js';

export {
  isKnown,
  type GraphCursors,
  type GraphErrorDetail,
  type GraphErrorResponse,
  type GraphPage,
  type GraphPaging,
  type GraphSuccessResponse,
  type KnownOr,
  type MessagingProduct,
  type UnknownProviderValue,
  type WhatsAppConnectionMetadata,
} from './common.js';

export {
  MESSAGE_ACCEPTANCE_STATUSES,
  type InteractiveBody,
  type InteractiveButtonAction,
  type InteractiveContent,
  type InteractiveFooter,
  type InteractiveHeader,
  type InteractiveListAction,
  type InteractiveListRow,
  type InteractiveListSection,
  type InteractiveMessageRequest,
  type InteractiveReplyButton,
  type MarkMessageReadRequest,
  type MarkMessageReadResponse,
  type MediaObject,
  type MessageAcceptanceStatus,
  type MessageContext,
  type OutboundMessageRequest,
  type SendMessageResponse,
  type SendMessageResponseContact,
  type SendMessageResponseMessage,
  type TemplateBodyComponent,
  type TemplateButtonComponent,
  type TemplateComponent,
  type TemplateCurrencyParameter,
  type TemplateDateTimeParameter,
  type TemplateHeaderComponent,
  type TemplateMediaParameter,
  type TemplateMessageContent,
  type TemplateMessageRequest,
  type TemplateParameter,
  type TemplateParameterType,
  type TemplateTextParameter,
  type TextMessageContent,
  type TextMessageRequest,
} from './messages.js';

export {
  TEMPLATE_CATEGORIES,
  TEMPLATE_QUALITY_SCORES,
  TEMPLATE_REJECTED_REASONS,
  TEMPLATE_STATUSES,
  type CreatableTemplateCategory,
  type CreateTemplateRequest,
  type CreateTemplateResponse,
  type DeleteTemplateRequest,
  type ListTemplatesQuery,
  type MessageTemplate,
  type MessageTemplatePage,
  type TemplateButtonType,
  type TemplateCategory,
  type TemplateComponentExample,
  type TemplateComponentFormat,
  type TemplateComponentType,
  type TemplateDefinitionButton,
  type TemplateDefinitionComponent,
  type TemplateOtpButtonType,
  type TemplateParameterFormat,
  type TemplateQualityScore,
  type TemplateQualityScoreValue,
  type TemplateRejectedReason,
  type TemplateStatus,
  type UpdateTemplateRequest,
} from './templates.js';

export {
  MESSAGING_LIMIT_TIERS,
  PHONE_NUMBER_FIELDS,
  PHONE_NUMBER_QUALITY_RATINGS,
  PHONE_NUMBER_STATUSES,
  type BusinessPhoneNumber,
  type BusinessPhoneNumberPage,
  type CodeVerificationStatus,
  type ListPhoneNumbersQuery,
  type MessagingLimitTier,
  type PhoneNumberAccountMode,
  type PhoneNumberHostPlatform,
  type PhoneNumberQualityRating,
  type PhoneNumberStatus,
  type RegisterPhoneNumberRequest,
  type RegisterPhoneNumberResponse,
  type SubscribeAppRequest,
  type SubscribeAppResponse,
  type SubscribedApp,
  type SubscribedAppsResponse,
  type UnifiedCertStatus,
  type WhatsAppBusinessAccount,
  type WhatsAppBusinessAccountPage,
} from './accounts.js';

export type {
  AccessTokenMetadata,
  EmbeddedSignupFailureReason,
  EmbeddedSignupResult,
  ExchangeAuthorizationCodeRequest,
  ExchangeAuthorizationCodeResponse,
  ExchangeAuthorizationCodeResult,
} from './signup.js';

export {
  INBOUND_MESSAGE_TYPES,
  MESSAGE_DELIVERY_STATUSES,
  TEMPLATE_STATUS_UPDATE_EVENTS,
  type AccountUpdateChange,
  type AccountUpdateValue,
  type ConversationCategory,
  type InboundButtonReply,
  type InboundInteractive,
  type InboundListReply,
  type InboundMessage,
  type InboundMessageContext,
  type InboundMessageType,
  type MessageDeliveryStatus,
  type MessageStatusEntry,
  type MessagesChange,
  type MessagesChangeValue,
  type PhoneNumberQualityEvent,
  type PhoneNumberQualityUpdateChange,
  type PhoneNumberQualityUpdateValue,
  type PricingModel,
  type PricingType,
  type StatusConversation,
  type StatusPricing,
  type TemplateStatusUpdateChange,
  type TemplateStatusUpdateEvent,
  type TemplateStatusUpdateValue,
  type UnknownChange,
  type WebhookChange,
  type WebhookContact,
  type WebhookEntry,
  type WebhookError,
  type WebhookMetadata,
  type WebhookPayload,
} from './webhooks.js';

export {
  NORMALIZED_EVENT_KINDS,
  type AccountUpdatedEvent,
  type InteractionReceivedEvent,
  type MessageDeliveredEvent,
  type MessageFailedEvent,
  type MessageReadEvent,
  type MessageReceivedEvent,
  type MessageSentEvent,
  type MessageStatusEvent,
  type NormalizedError,
  type NormalizedEventBase,
  type NormalizedEventKind,
  type NormalizedPhoneContext,
  type NormalizedWhatsAppEvent,
  type PhoneStatusUpdatedEvent,
  type TemplateStatusUpdatedEvent,
  type UnknownEvent,
} from './events.js';
